/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 19-apr-2024 13:05:08 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

/* Drop Database Create Database */

DROP DATABASE IF EXISTS udrzba;
CREATE DATABASE udrzba;
USE udrzba;

DROP TABLE IF EXISTS `Cinnost_opravy` CASCADE
;

DROP TABLE IF EXISTS `Cinnost_udrzby` CASCADE
;

DROP TABLE IF EXISTS `Dodavatel` CASCADE
;

DROP TABLE IF EXISTS `Kategoria` CASCADE
;

DROP TABLE IF EXISTS `Nahradny_diel` CASCADE
;

DROP TABLE IF EXISTS `Nachadza` CASCADE
;

DROP TABLE IF EXISTS `Oprava` CASCADE
;

DROP TABLE IF EXISTS `Planovana_udrzba` CASCADE
;

DROP TABLE IF EXISTS `Porucha` CASCADE
;

DROP TABLE IF EXISTS `Pouziva` CASCADE
;

DROP TABLE IF EXISTS `Pouzivatel` CASCADE
;

DROP TABLE IF EXISTS `Poziadavka_na_nahradny_diel` CASCADE
;

DROP TABLE IF EXISTS `Priloha` CASCADE
;

DROP TABLE IF EXISTS `Rola` CASCADE
;

DROP TABLE IF EXISTS `Skladovy_doklad` CASCADE
;

DROP TABLE IF EXISTS `Stroj` CASCADE
;

DROP TABLE IF EXISTS `Uvedeny` CASCADE
;

DROP TABLE IF EXISTS `Zamestnanec` CASCADE
;

/* Create Tables */

CREATE TABLE `Cinnost_opravy`
(
	`Cin_nazov` VARCHAR(50) NOT NULL,
	`Cinnost_opravyID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Cinnost_opravy` PRIMARY KEY (`Cinnost_opravyID` ASC)
)

;

CREATE TABLE `Cinnost_udrzby`
(
	`Cin_datum_udrzby` DATETIME NOT NULL,
	`Cin_odpracovane_hodiny` DOUBLE(10,2) UNSIGNED NOT NULL,
	`Cin_poznamka` VARCHAR(200) NULL,
	`Cinnost_udrzbyID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Planovana_udrzbaID` INT UNSIGNED NOT NULL,
	`PouzivatelID` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_Cinnost_udrzby` PRIMARY KEY (`Cinnost_udrzbyID` ASC)
)

;

CREATE TABLE `Dodavatel`
(
	`Dod_nazov` VARCHAR(50) NOT NULL,
	`Dod_email` VARCHAR(50) NULL,
	`Dod_telefon` VARCHAR(20) NULL,
	`Dod_ulica_a_cislo` VARCHAR(50) NULL,
	`Dod_mesto` VARCHAR(50) NULL,
	`Dod_psc` VARCHAR(5) NULL,
	`Dod_stat` VARCHAR(50) NULL,
	`Dod_ico` VARCHAR(8) NULL,
	`Dod_dic` VARCHAR(10) NULL,
	`Dod_ic_dph` VARCHAR(12) NULL,
	`DodavatelID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Dodavatel` PRIMARY KEY (`DodavatelID` ASC)
)

;

CREATE TABLE `Kategoria`
(
	`Kat_nazov` VARCHAR(50) NOT NULL,
	`KategoriaID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Kategoria` PRIMARY KEY (`KategoriaID` ASC)
)

;

CREATE TABLE `Nahradny_diel`
(
	`Diel_evidencne_cislo` VARCHAR(20) NOT NULL,
	`Diel_nazov` VARCHAR(50) NOT NULL,
	`Diel_popis` VARCHAR(100) NULL,
	`Diel_jednotka` VARCHAR(10) NOT NULL,
	`Diel_mnozstvo` INT UNSIGNED NOT NULL,
	`Diel_umiestnenie` VARCHAR(30) NOT NULL,
	`Diel_datum_prevzatia` DATE NULL,
	`Diel_zarucna_doba` INT UNSIGNED NULL,
	`Nahradny_dielID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`KategoriaID` INT UNSIGNED NOT NULL,
	`StrojID` INT UNSIGNED NULL,
	CONSTRAINT `PK_Nahradny_diel` PRIMARY KEY (`Nahradny_dielID` ASC)
)

;

CREATE TABLE `Nachadza`
(
	`Dok_nazov_dielu` VARCHAR(50) NOT NULL,
	`Dok_jednotka` VARCHAR(10) NOT NULL,
	`Dok_mnozstvo` INT UNSIGNED NOT NULL,
	`Dok_cena_za_jednotku` DOUBLE(10,2) UNSIGNED NOT NULL,
	`Dok_celkova_cena` DOUBLE(10,2) UNSIGNED NOT NULL,
	`NachadzaID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Skladovy_dokladID` INT UNSIGNED NOT NULL,
	`Nahradny_dielID` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_Nachadza` PRIMARY KEY (`NachadzaID` ASC)
)

;

CREATE TABLE `Oprava`
(
	`Opr_datum_opravy` DATETIME NOT NULL,
	`Opr_popis` VARCHAR(100) NULL,
	`Opr_odpracovane_hodiny` INT NOT NULL,
	`OpravaID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Cinnost_opravyID` INT UNSIGNED NOT NULL,
	`PouzivatelID` INT UNSIGNED NOT NULL,
	`PoruchaID` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_Oprava` PRIMARY KEY (`OpravaID` ASC)
)

;

CREATE TABLE `Planovana_udrzba`
(
	`Plan_nazov` VARCHAR(50) NOT NULL,
	`Plan_datum_cas_od` DATETIME NOT NULL,
	`Plan_datum_cas_do` DATETIME NOT NULL,
	`Plan_popis` VARCHAR(100) NULL,
	`Plan_perioda` VARCHAR(20) NOT NULL,
	`Plan_aktivna` BOOL NOT NULL,
	`Planovana_udrzbaID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`StrojID` INT UNSIGNED NULL,
	`PouzivatelID` INT UNSIGNED NULL,
	CONSTRAINT `PK_Planovana_udrzba` PRIMARY KEY (`Planovana_udrzbaID` ASC)
)

;

CREATE TABLE `Porucha`
(
	`Por_nazov` VARCHAR(50) NOT NULL,
	`Por_popis` VARCHAR(100) NULL,
	`Por_stav` INT NOT NULL,
	`Por_datum_vzniku` DATETIME NOT NULL,
	`Por_datum_pridelenia` DATETIME NULL,
	`PoruchaID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`StrojID` INT UNSIGNED NULL,
	`PouzivatelID` INT UNSIGNED NULL,
	CONSTRAINT `PK_Porucha` PRIMARY KEY (`PoruchaID` ASC)
)

;

CREATE TABLE `Pouziva`
(
	`Opr_nazov_dielu` VARCHAR(50) NULL,
	`Opr_mnozstvo` INT UNSIGNED NOT NULL,
	`Opr_jednotka` VARCHAR(20) NOT NULL,
	`PouzivaID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Nahradny_dielID` INT UNSIGNED NULL,
	`PoruchaID` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_Pouziva` PRIMARY KEY (`PouzivaID` ASC)
)

;

CREATE TABLE `Pouzivatel`
(
	`Pouz_meno` VARCHAR(50) NOT NULL,
	`Pouz_heslo` VARCHAR(60) NOT NULL,
	`PouzivatelID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`RolaID` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_Pouzivatel` PRIMARY KEY (`PouzivatelID` ASC)
)

;

CREATE TABLE `Poziadavka_na_nahradny_diel`
(
	`Poz_stav` INT NOT NULL,
	`Poz_poznamka` VARCHAR(200) NULL,
	`Poziadavka_na_nahradny_dielID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`PouzivatelID` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_Poziadavka_na_nahradny_diel` PRIMARY KEY (`Poziadavka_na_nahradny_dielID` ASC)
)

;

CREATE TABLE `Priloha`
(
	`Nazov_suboru` VARCHAR(50) NOT NULL,
	`PrilohaID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`StrojID` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_Priloha` PRIMARY KEY (`PrilohaID` ASC)
)

;

CREATE TABLE `Rola`
(
	`Rola_nazov` VARCHAR(30) NOT NULL,
	`RolaID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Rola` PRIMARY KEY (`RolaID` ASC)
)

;

CREATE TABLE `Skladovy_doklad`
(
	`Dok_evidencne_cislo` INT UNSIGNED NOT NULL,
	`Dok_typ` INT UNSIGNED NOT NULL,
	`Dok_datum` DATE NOT NULL,
	`Dok_suma` DOUBLE(10,2) UNSIGNED NOT NULL,
	`Dok_poznamka` VARCHAR(200) NULL,
	`Skladovy_dokladID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`DodavatelID` INT UNSIGNED NULL,
	CONSTRAINT `PK_Skladovy_doklad` PRIMARY KEY (`Skladovy_dokladID` ASC)
)

;

CREATE TABLE `Stroj`
(
	`Stroj_nazov` VARCHAR(50) NOT NULL,
	`Stroj_popis` VARCHAR(100) NULL,
	`Stroj_vyrobca` VARCHAR(30) NOT NULL,
	`Stroj_umiestnenie` VARCHAR(30) NOT NULL,
	`Stroj_datum_vyroby` DATE NULL,
	`Stroj_vyrobne_cislo` VARCHAR(20) NOT NULL,
	`Stroj_evidencne_cislo` VARCHAR(20) NOT NULL,
	`Stroj_datum_prevzatia` DATE NULL,
	`Stroj_zarucna_doba` INT NULL,
	`StrojID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`DodavatelID` INT UNSIGNED NULL,
	CONSTRAINT `PK_Stroj` PRIMARY KEY (`StrojID` ASC)
)

;

CREATE TABLE `Uvedeny`
(
	`Poz_nazov_dielu` VARCHAR(50) NULL,
	`Poz_mnozstvo` INT UNSIGNED NOT NULL,
	`Poz_jednotka` varchar(20) NOT NULL,
	`UvedenyID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Nahradny_dielID` INT UNSIGNED NULL,
	`Poziadavka_na_nahradny_dielID` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_Uvedeny` PRIMARY KEY (`UvedenyID` ASC)
)

;

CREATE TABLE `Zamestnanec`
(
	`Zam_meno` VARCHAR(20) NOT NULL,
	`Zam_priezvisko` VARCHAR(50) NOT NULL,
	`Zam_datum_narodenia` DATE NULL,
	`Zam_email` VARCHAR(50) NOT NULL,
	`Zam_telefon` VARCHAR(20) NOT NULL,
	`Zam_ulica_a_cislo` VARCHAR(50) NOT NULL,
	`Zam_mesto` VARCHAR(50) NOT NULL,
	`Zam_psc` VARCHAR(5) NOT NULL,
	`Zam_pozicia` VARCHAR(30) NOT NULL,
	`Zam_datum_nastupu` DATE NULL,
	`Zam_poznamka` VARCHAR(200) NULL,
	`ZamestnanecID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`PouzivatelID` INT UNSIGNED NOT NULL,
	CONSTRAINT `PK_Zamestnanec` PRIMARY KEY (`ZamestnanecID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Cinnost_udrzby` 
 ADD CONSTRAINT `FK_Cinnost_udrzby_sa_vykonava`
	FOREIGN KEY (`Planovana_udrzbaID`) REFERENCES `Planovana_udrzba` (`Planovana_udrzbaID`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `Cinnost_udrzby` 
 ADD CONSTRAINT `FK_Cinnost_udrzby_vykonava`
	FOREIGN KEY (`PouzivatelID`) REFERENCES `Pouzivatel` (`PouzivatelID`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `Nahradny_diel` 
 ADD CONSTRAINT `FK_Nahradny_diel_patri_do`
	FOREIGN KEY (`KategoriaID`) REFERENCES `Kategoria` (`KategoriaID`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `Nahradny_diel` 
 ADD CONSTRAINT `FK_Nahradny_diel_patri_ku`
	FOREIGN KEY (`StrojID`) REFERENCES `Stroj` (`StrojID`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `Nachadza` 
 ADD CONSTRAINT `FK_Nachadza_Skladovy_doklad`
	FOREIGN KEY (`Skladovy_dokladID`) REFERENCES `Skladovy_doklad` (`Skladovy_dokladID`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `Nachadza` 
 ADD CONSTRAINT `FK_Nachadza_Nahradny_diel`
	FOREIGN KEY (`Nahradny_dielID`) REFERENCES `Nahradny_diel` (`Nahradny_dielID`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `Oprava` 
 ADD CONSTRAINT `FK_Oprava_obsahuje`
	FOREIGN KEY (`Cinnost_opravyID`) REFERENCES `Cinnost_opravy` (`Cinnost_opravyID`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `Oprava` 
 ADD CONSTRAINT `FK_Oprava_vykonava`
	FOREIGN KEY (`PouzivatelID`) REFERENCES `Pouzivatel` (`PouzivatelID`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `Oprava` 
 ADD CONSTRAINT `FK_Oprava_odstranuje`
	FOREIGN KEY (`PoruchaID`) REFERENCES `Porucha` (`PoruchaID`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `Planovana_udrzba` 
 ADD CONSTRAINT `FK_Planovana_udrzba_sa_vykonava_na`
	FOREIGN KEY (`StrojID`) REFERENCES `Stroj` (`StrojID`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `Planovana_udrzba` 
 ADD CONSTRAINT `FK_Planovana_udrzba_ma_pridelenu`
	FOREIGN KEY (`PouzivatelID`) REFERENCES `Pouzivatel` (`PouzivatelID`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `Porucha` 
 ADD CONSTRAINT `FK_Porucha_nastala_na`
	FOREIGN KEY (`StrojID`) REFERENCES `Stroj` (`StrojID`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `Porucha` 
 ADD CONSTRAINT `FK_Porucha_ma_pridelenu`
	FOREIGN KEY (`PouzivatelID`) REFERENCES `Pouzivatel` (`PouzivatelID`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `Pouziva` 
 ADD CONSTRAINT `FK_Pouziva_Porucha`
	FOREIGN KEY (`PoruchaID`) REFERENCES `Porucha` (`PoruchaID`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `Pouziva` 
 ADD CONSTRAINT `FK_Pouziva_Nahradny_diel`
	FOREIGN KEY (`Nahradny_dielID`) REFERENCES `Nahradny_diel` (`Nahradny_dielID`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `Pouzivatel` 
 ADD CONSTRAINT `FK_Pouzivatel_ma_pridelenu`
	FOREIGN KEY (`RolaID`) REFERENCES `Rola` (`RolaID`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `Poziadavka_na_nahradny_diel` 
 ADD CONSTRAINT `FK_Poziadavka_na_nahradny_diel_podava`
	FOREIGN KEY (`PouzivatelID`) REFERENCES `Pouzivatel` (`PouzivatelID`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `Priloha` 
 ADD CONSTRAINT `FK_Priloha_patri_ku`
	FOREIGN KEY (`StrojID`) REFERENCES `Stroj` (`StrojID`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `Skladovy_doklad` 
 ADD CONSTRAINT `FK_Skladovy_doklad_je_zapisany_na`
	FOREIGN KEY (`DodavatelID`) REFERENCES `Dodavatel` (`DodavatelID`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `Stroj` 
 ADD CONSTRAINT `FK_Stroj_dodava`
	FOREIGN KEY (`DodavatelID`) REFERENCES `Dodavatel` (`DodavatelID`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `Uvedeny` 
 ADD CONSTRAINT `FK_Uvedeny_Nahradny_diel`
	FOREIGN KEY (`Nahradny_dielID`) REFERENCES `Nahradny_diel` (`Nahradny_dielID`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `Uvedeny` 
 ADD CONSTRAINT `FK_Uvedeny_Poziadavka_na_nahradny_diel`
	FOREIGN KEY (`Poziadavka_na_nahradny_dielID`) REFERENCES `Poziadavka_na_nahradny_diel` (`Poziadavka_na_nahradny_dielID`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `Zamestnanec` 
 ADD CONSTRAINT `FK_Zamestnanec_Pouzivatel`
	FOREIGN KEY (`PouzivatelID`) REFERENCES `Pouzivatel` (`PouzivatelID`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1
; 
